version: "3"

services:
  app:
    build: ./flask_app/
    ports:
      - "8000:8000"
    environment:
      STATSD_HOST: "statsd-exporter"
      STATSD_PORT: "9125"
    volumes:
      - ./flask_app/logs:/var/log/flask

  statsd-exporter:
    image: prom/statsd-exporter:latest
    ports:
      - "9125:9125"
      - "9102:9102"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - /home/navkaransingh/work_projects/flask-monitoring/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /home/navkaransingh/work_projects/flask-monitoring/etc/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - /home/navkaransingh/work_projects/flask-monitoring/etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - /home/navkaransingh/work_projects/flask-monitoring/etc/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
      - loki
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"

  loki:
    image: grafana/loki:3.1.2 # or your custom image if you've built it
    container_name: loki
    ports:
      - "3100:3100"  # HTTP port for Loki
      - "9095:9095"  # gRPC port for Loki
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml  # Mount the updated configuration file
    environment:
      - LOki_VERSION=3.1.2  # Optional, to pass environment variables if needed
    restart: always  # Optional: Restart container if it fails

  promtail:
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - ./flask_app/logs:/var/log/flask
      - /home/navkaransingh/work_projects/flask-monitoring/etc/promtail/config.yml:/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    command:
      - '--config.file=/etc/promtail/promtail-config.yaml'
