server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/promtail-positions.yaml

scrape_configs:
  - job_name: "flask-logs"
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "flask-logs"
          __path__: /var/log/flask/app.log
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}' # Timestamp regex for grouping tracebacks
