global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape StatsD Exporter metrics
  - job_name: "statsd-exporter"
    static_configs:
      - targets: ["statsd-exporter:9102"]

  # Scrape Node Exporter metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

